### ISSUE TITLE
chaofanat/EnToZhAPI 这个docker 拉取报错

### ISSUE THREAD

**Issue by zqzess** [chaofanat/django-projecet-template#1]
gitee 巨麻烦，提 issue 要登录，完了还要什么身份认证，所以来 github 提，抱歉

<img width="1370" alt="image" src="https://github.com/user-attachments/assets/9104595c-a571-4443-8565-23a272b791db">

**Comment by chaofanat** [comment]
嗯，我阿里云的容器镜像服务之前设为私有了，现在已经打开，应该可以使用了，但是不一定会长期开放，建议自己搭建容器镜像服务，然后修改Dockerfile文件中的底座容器地址就好了。
![image](https://github.com/user-attachments/assets/d984996e-9e7b-4e40-8205-d92b5939a960)
